### ISSUE TITLE
Problems in Ethereum default experience

### ISSUE THREAD

**Issue by TravisBacon** [ooibc88/blockbench#62]
Well I used docker containers to creat 2 server nodes and 2 client nodes . The servers' ip are 10.0.0.3 and 10.0.0.4 while the clients's ip are 10.0.0.100 and 10.0.0.99 .
Then ran the command "run-bench.sh 2 1 2 8" and error occurred .

Error: Invalid number of input parameters to RPC method
    at web3.js:3133:20
    at web3.js:5008:15
    at web3.js:5051:5
    at web3.js:5075:23
    at <anonymous>:1:1

Error: Invalid number of input parameters to RPC method
    at web3.js:3133:20
    at web3.js:5008:15
    at web3.js:5051:5
    at web3.js:5075:23
    at <anonymous>:1:1

done node 10.0.0.3

Error: Invalid number of input parameters to RPC method
    at web3.js:3133:20
    at web3.js:5008:15
    at web3.js:5051:5
    at web3.js:5075:23
    at <anonymous>:1:1

Error: Invalid number of input parameters to RPC method
    at web3.js:3133:20
    at web3.js:5008:15
    at web3.js:5051:5
    at web3.js:5075:23
    at <anonymous>:1:1

done node 10.0.0.4

I have located the code which may cause error according to other messages on the terminal as follows :+1: 

start-mining.sh
#!/bin/bash
cd `dirname ${BASH_SOURCE-$0}`
. env.sh

nohup geth --datadir=$ETH_DATA --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcport "8000" --rpccorsdomain "*" --gasprice 0 --maxpeers 32 --networkid 9119 --unlock 0 --password <(echo -n "") --mine --minerthreads 8 > $ETH_DATA/../eth_log 2>&1 &

sleep 1

for com in `cat $ETH_HOME/addPeer.txt`; do
  geth --exec $com attach ipc:/$ETH_DATA/geth.ipc
done

Here , I am not sure about the reasons . Maybe the format of "geth" command in the code is not permitted in the eth version 1.8?

I need your help !!! Much obliged!

**Comment by TravisBacon** [comment]
Well I found that 
    for com in cat $ETH_HOME/addPeer.txt; do
        geth --exec $com attach ipc:/$ETH_DATA/geth.ipc
    done
caused the error 

I used "cat addPeer.txt" in one server node container and got the result as follows:
admin.addPeer()
admin.addPeer()
So it obviously lacks something in the brackets .

The script used for creating addPeer.txt is gather.sh and enode.sh
